### ISSUE TITLE
error: file format not support, for supported file formats...

### ISSUE THREAD

**Issue by tthgithub** [MouseLand/FaceMap#10]
ie your test videos even, it says file format not supported. im on windows 10, followed your instructions. cannot get it to work!!!

**Comment by carsen-stringer** [comment]
are you using the python or matlab version? I've updated the install documentation and the package for the python version

**Comment by carsen-stringer** [comment]
this might be related to issue #11 

please try
```
pip install facemap --upgrade
```
and try again

I'm closing this for now without more info to go on. please comment and I'll reopen it
