### ISSUE TITLE
BUG: unsure how to extract data from pose keypoints

### ISSUE THREAD

**Issue by Chiara-toschi** [MouseLand/facemap#100]
### Version information:

numpy version: 1.23.5
python version: 3.8.16

### Describe the issue:

Hi, this is perhaps a stupid question but I can't figure out how to use/extract data from the keypoints on the face of the animal. I tried setting it as an ROI but it's giving me weird data. can you help me and if possible provide a more detailed documentation? Thank you!

**Comment by Atika-Syeda** [comment]
Hi @Chiara-toschi, do you need help with generating keypoints using Facemap or using the `*.h5` output file from facemap?
You can find the instructions for generating and loading keypoints [here](https://github.com/MouseLand/facemap/blob/main/docs/pose_tracking_gui_tutorial.md).
