### ISSUE TITLE
BUG: Latest numpy breaks ROIs

### ISSUE THREAD

**Issue by jonahpearl** [MouseLand/facemap#102]
### Version information:

numpy version: 1.24.0
python version: 3.8.16
[... a lot of numba jit warnings...]
** TORCH CUDA version installed and working. **

### Describe the issue:

np.bool has been fully removed (was previously deprecated) and this breaks the facemap gui. Reverting to numpy==1.21.0 solved it for now. The numpy folks say you can drop in the standard python `bool` as a replacement. Another easy fix would be to pin the numpy version in requirements.txt. Your call!

### Error message:

```shell
Sorry I forgot to grab this, but you can reproduce by installing a new facemap repo, doing `python -m pip install facemap[gui]`, and then trying to load an ROI onto a movie in the GUI.
```

**Comment by Atika-Syeda** [comment]
Hi, thanks for the suggestion. It will be fixed in the next release.
