### ISSUE TITLE
BUG: savepath issue within the run function in process.py

### ISSUE THREAD

**Issue by sidhulyalkar** [MouseLand/facemap#105]
### Version information:

Running version `1.0.1.dev7+gb40a61e`, via git clone https://github.com/MouseLand/facemap.git

### Describe the issue:

Currently the way that savepath is obtained errors when the savepath is not included in the proc(previous parameters) input and a savepath is specified, when a proc input is specified. 

Line 703 in process.py, inside of the run function: 
`savepath = proc["savepath"] if savepath is not None else savepath
`
should be changed to ->
`savepath = proc["savepath"] if savepath is None else savepath
`

**Comment by Atika-Syeda** [comment]
Hi @sidhulyalkar can you please try installing the pip version and let us know if you get the same error.

**Comment by sahrlund** [comment]
Hi, 
I am having the same issue (with a pip installation) when I try to batch process multiple videos with a single ROI saved to each video. One video with a ROI runs just fine. 

Traceback (most recent call last):
  File "C:\Users\SOFIE\anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py", line 1217, in process_batch
    savename = process.run(
  File "C:\Users\SOFIE\anaconda3\envs\facemap\lib\site-packages\facemap\process.py", line 706, in run
    savepath = proc["savepath"] if savepath is not None else savepath
KeyError: 'savepath'



numpy version: 1.24.3
python version: 3.8.17
QGridLayoutEngine::addItem: Cell (2, 0) already taken
QGridLayoutEngine::addItem: Cell (3, 0) already taken
** TORCH CUDA version installed and working. **
version 0.2.0

**Comment by Atika-Syeda** [comment]
Hi @sidhulyalkar @sahrlund thanks for identifying the bug and suggesting a solution. The latest version on the main branch is fixed.
