### ISSUE TITLE
BUG: Error in reading frame?

### ISSUE THREAD

**Issue by AbyFlores** [MouseLand/facemap#106]
### Version information:

File "C:\Apps\anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py", line 1069, in next_frame
    self.imgs[i][:, :, :, 2] = im[i]
IndexError: list index out of range
Error reading frame
![Frame reading error ROI](https://github.com/MouseLand/facemap/assets/63807560/0762f137-e8e6-468e-95f2-6bc41788204c)

### Describe the issue:

Processing gets stuck at 66723/84239 frames and I'm unsure how to resolve this issue?

**Comment by Atika-Syeda** [comment]
Hi @AbyFlores could you please provide more information on how you loaded the videos and added the ROIs?
