### ISSUE TITLE
Problem with batch processing

### ISSUE THREAD

**Issue by ratliffj** [MouseLand/facemap#11]
Hi Carsen

Thanks so much for creating this for the community to use. It has already been quite helpful for me.

I am currently running into trouble with serial batch processing of my videos. I am able to process the videos individually but when I try to batch process them I get the following error about unsupported movie files:

single camera
['//192.168.1.200/renatalab/JR_MARCIN/JR_0731_noinj/JR_0731_12\\pupil_2019-07-31-190346-0000.avi', '//192.168.1.200/renatalab/JR_MARCIN/JR_0731_noinj/JR_0731_12\\pupil_2019-07-31-190346-0001.avi', '//192.168.1.200/renatalab/JR_MARCIN/JR_0731_noinj/JR_0731_12\\pupil_2019-07-31-190346-0002.avi', '//192.168.1.200/renatalab/JR_MARCIN/JR_0731_noinj/JR_0731_12\\pupil_2019-07-31-190346-0003.avi', '//192.168.1.200/renatalab/JR_MARCIN/JR_0731_noinj/JR_0731_12\\pupil_2019-07-31-190346-0004.avi']
pyavreaderindexed used - may be slower (try installing pims github version)
ERROR: not a supported movie file
[Errno 13] Permission denied: '/'

If I try to use the "Open Movie Folder" button and open only one movie, I get a different set of errors:

[['//192.168.1.200/renatalab/JR_MARCIN/JR_0731_noinj/JR_0731_12\\pupil_2019-07-31-190346-0000.avi']]
pyavreaderindexed used - may be slower (try installing pims github version)
deprecated pixel format used, make sure you did set range correctly
Traceback (most recent call last):
  File "C:\Users\renatalab\Anaconda3\envs\facemap\lib\site-packages\facemap\gui.py", line 473, in open_folder
    self.load_movies()
  File "C:\Users\renatalab\Anaconda3\envs\facemap\lib\site-packages\facemap\gui.py", line 742, in load_movies
    self.jump_to_frame()
  File "C:\Users\renatalab\Anaconda3\envs\facemap\lib\site-packages\facemap\gui.py", line 833, in jump_to_frame
    self.img = self.get_frame(self.cframe)
  File "C:\Users\renatalab\Anaconda3\envs\facemap\lib\site-packages\facemap\gui.py", line 850, in get_frame
    img.append(np.array(vs[cframe - self.cumframes[ivid]]))
  File "C:\Users\renatalab\Anaconda3\envs\facemap\lib\site-packages\slicerator\__init__.py", line 188, in __getitem__
    return self._get(indices)
  File "C:\Users\renatalab\Anaconda3\envs\facemap\lib\site-packages\pims\base_frames.py", line 148, in __getitem__
    return self.get_frame(key)
  File "C:\Users\renatalab\Anaconda3\envs\facemap\lib\site-packages\pims\pyav_reader.py", line 377, in get_frame
    result = _to_nd_array(frame)
  File "C:\Users\renatalab\Anaconda3\envs\facemap\lib\site-packages\pims\pyav_reader.py", line 29, in _to_nd_array
    frame_arr.shape = (frame.height, frame.width, -1)
ValueError: cannot reshape array of size 440832 into shape (328,444,newaxis)

I am using the python gui on Windows 10 and acquire my videos using ptgrey cameras using their software that splits the movies when they reach a certain size.

**Comment by carsen-stringer** [comment]
oh I see the issue - the paths have back slashes. not sure why that's happening, I will add a fix for that.

can you process these many files together by selecting them in a movie folder? facemap will then concatenate your results for you (because these were all the same session so you'd like them that way anyway). when the GUI asks: "are you processing multiple videos taken simultaneously?" say NO

**Comment by ratliffj** [comment]
Thanks for getting back.

I am not able to process the videos by selecting a folder and saying "NO". That is the sequence that gives me these errors. I have been able to process these videos by selecting the folder and saying "YES". This didn't seem correct to me at first but it seems to work and allows me to batch process the files concatenating the results in the output .mat file. I can send over some of the files too if that would be helpful.

**Comment by carsen-stringer** [comment]
Sorry I had a bug in the file listing for single cameras (like you have), I think I've fixed this. Try it out now. Answering "YES" worked because your files have the same first 4 letters (it doesn't think they're the same view even though you said they were because they aren't e.g. cam1...avi, cam2...avi, ... etc). Answering "NO" should now work as it's supposed to.
```
pip install facemap --upgrade
```
