### ISSUE TITLE
ROI Inspection in Multiple Video Files Using GUI

### ISSUE THREAD

**Issue by Annaaasen** [MouseLand/facemap#121]
### Version information:

numpy version: 1.21.0
python version: 3.8.16

### Describe the issue:

Firstly, I wanted to express my gratitude for creating Facemap; it is a wonderful tool!

I'm currently working on a project where I need to process several sequential video files. I've been using the GUI to create a region of interest (ROI) in one of the videos. However, I've encountered a challenge. After creating the ROI, I'd like to assess its suitability in other videos before proceeding with the processing. Unfortunately, it seems that the GUI restricts me to view the ROI only in the video where it was initially created, possibly due to “filenames” saved in the npy-file.

Could you confirm if my understanding is correct or if there's a way to examine the same ROI across multiple video files before I commence the processing? It would be greatly appreciated. 

### Error message:

when loading ROI in GUI on avi file different to the one it was created on:

```shell
OpenCV: Couldn't read video stream from file "E:/AVI/<filename>.avi"
QGraphicsScene::removeItem: item 0x600000c946f0's scene (0x0) is different from this scene (0x600003787880)
Error reading frame
Error reading frame
Error reading frame
Traceback (most recent call last):
  File "/Users/miniconda/envs/facemap/lib/python3.8/site-packages/facemap/gui/menus.py", line 20, in <lambda>
    load_proc.triggered.connect(lambda: io.open_proc(parent))
  File "/Users/miniconda/envs/facemap/lib/python3.8/site-packages/facemap/gui/io.py", line 123, in open_proc
    good = load_movies(parent, filelist=parent.filenames)
  File "/Users/miniconda/envs/facemap/lib/python3.8/site-packages/facemap/gui/io.py", line 347, in load_movies
    parent.jump_to_frame()
  File "/Users/miniconda/envs/facemap/lib/python3.8/site-packages/facemap/gui/gui.py", line 1048, in jump_to_frame
    self.next_frame()
  File "/Users/miniconda/envs/facemap/lib/python3.8/site-packages/facemap/gui/gui.py", line 1069, in next_frame
    self.imgs[i][:, :, :, 2] = im[i]
IndexError: list index out of range
```

**Comment by Atika-Syeda** [comment]
Hi @Annaaasen yes, you're right the load ROI only works with the filename used for creating it. You could load the saved ROIs file in a notebook to visualize them on another video.

**Comment by Annaaasen** [comment]
Okay, thank you:)
