### ISSUE TITLE
Corneal Reflection does not work for Pupil ROI

### ISSUE THREAD

**Issue by maimechevee** [MouseLand/facemap#13]
We tried to add corneal reflections to help the program better capture the mouse pupil. While the ROI responded to added corneal reflections, it ignored the corneal reflections after processing the ROIs and did not yield pupil size results as accurate as shown by the ROI before processing. Thank you!

**Comment by ngf7** [comment]
Although corneal reflections aren't loaded into the GUI immediately after processing, they are saved within the processed file and will affect the ROI. You can quit facemap, reopen, then load the processed .npy for a fix.
