### ISSUE TITLE
BUG: 'motion' variable is an array of ideantical values although avgmotion return a reasonable output

### ISSUE THREAD

**Issue by magdalenasabat** [MouseLand/facemap#131]
### Version information:

facemap version: 1.0.4
platform: linux
python version: 3.8.13
torch version: 1.11.0+cu102
numpy version: 1.24.4

### Describe the issue:

The output of proccessed video returns an array of identical values altough avg motion and motion SVD returns a reasonable output.

**Comment by Atika-Syeda** [comment]
Hi @magdalenasabat  could you please print 'motion' variable and share the output. Were you processing videos with any ROIs? If so, which ones?

**Comment by magdalenasabat** [comment]
Hello, no ROIs.

The output: 

```
print(vid['motion'])
[array([11303661., 11303661., 11303661., ..., 11303661., 11303661.,
       11303661.], dtype=float32)]

print(np.unique(vid['motion']))
[11303661.]

```

**Comment by magdalenasabat** [comment]
I might have found the bug, tell me what you think:

 M, which is later assigned to the motion variable in the output, is defined in  process.py  line 340 - 350

```
    if fullSVD:
        ncomps_mot = U_mot[0].shape[-1]
        ncomps_mov = U_mov[0].shape[-1]
        V_mot = [np.zeros((nframes, ncomps_mot), np.float32)] if motSVD else []
        V_mov = [np.zeros((nframes, ncomps_mov), np.float32)] if movSVD else []
        M = [np.zeros((nframes), np.float32)]
    else:
        V_mot = [np.zeros((0, 1), np.float32)] if motSVD else []
        V_mov = [np.zeros((0, 1), np.float32)] if movSVD else []
        M = [np.zeros((0,), np.float32)]

```

so it's a list with one element, the numpy array,
then in line  line 457 (this is an example with fullSVD):

```
                    if fullSVD:
                        M[t : t + imbin_mot.shape[0]] += imbin_mot.sum(axis=(-2, -1))
```

which somehow works on te first video chunk, but not the following, if changed to
```
                    if fullSVD:
                        M[0][t : t + imbin_mot.shape[0]] += imbin_mot.sum(axis=(-2, -1))
```
so indexing into the list then numpy array, the output variable starts to make more sense, i.e. 

![image](https://github.com/MouseLand/facemap/assets/55433393/8766c632-fcef-4662-8923-1094a70fe072)

But still doesn't lok like raw motion, which seems to be defined in  line 453 
```
imbin_mot = np.abs(np.diff(imbin, axis=0))
```

what do you think?

**Comment by Atika-Syeda** [comment]
thanks for finding the bug and fixing it. I'll push a new release to change the line.
