### ISSUE TITLE
DOC: <Finetune model to refine keypoints for a video>

### ISSUE THREAD

**Issue by aubrey1124** [MouseLand/facemap#135]
### Issue with current documentation:

<img width="1093" alt="截屏2023-11-29 19 59 25" src="https://github.com/MouseLand/facemap/assets/152392922/465ada66-a8cc-4525-b53a-7d3c144fbcf5">

### Idea or request for content:

sorry to bother,i followed the guidance ,while i tried to finetune the model,and i couldnt find how to approach the step 3. actually after i chose the file in the step 2,the window closed and nothing coming next,no window appeared,just nothing happened. it might be a very simple and stupid question,but i really need some help!!!

**Comment by aubrey1124** [comment]
i cant find how to Select training data and set training parameters

**Comment by Atika-Syeda** [comment]
Hi @aubrey1124  can you please provide more info about which OS you're using? if it's a mac then the window doesn't close but is hidden behind other windows. Does facemap remain open after you select output folder path?

**Comment by aubrey1124** [comment]
I use mac m2 silicon, and it's 13.3.1 version.

**Comment by aubrey1124** [comment]
wow! thanks!! it really helps!! it does a mac ,m2 silicon,13.3.1.

**Comment by aubrey1124** [comment]
hey i downloaded the neural data yesterday before you answered . it seems the data couldnt be loaded into the face map
<img width="728" alt="截屏2023-12-01 12 22 30" src="https://github.com/MouseLand/facemap/assets/152392922/b934b033-5037-4b53-904b-b3d91cb90af8">
<img width="1135" alt="截屏2023-12-01 12 23 04" src="https://github.com/MouseLand/facemap/assets/152392922/9c0a4545-2e36-4f77-99ce-daec9a35631c">
i tried to download the numpy version to 1.16 but my Mac cant compatible to that version. currently the numpy version is the latest. Anther trouble here , i wonder the neural_data_sensorimotor.zip contains the .npz,and i transform it to .npy loaded to the facemap, no matter the one-dimensional array and two-dimensional array ,it just dont work. i think the trouble is somewhere in the code need to set "data = np.load(file_path, allow_pickle=True)"
<img width="594" alt="截屏2023-12-01 12 45 54" src="https://github.com/MouseLand/facemap/assets/152392922/c155f8a9-34ee-4cc0-8b2b-16e2f5407254">
<img width="1232" alt="截屏2023-12-01 12 46 41" src="https://github.com/MouseLand/facemap/assets/152392922/f12cb274-d0c3-445a-878a-2084e6992293">
<img width="1232" alt="截屏2023-12-01 12 47 51" src="https://github.com/MouseLand/facemap/assets/152392922/246a3fd4-1b9e-4506-9cf5-5051e5ed8e3f">
