### ISSUE TITLE
bug report about neural date load

### ISSUE THREAD

**Issue by aubrey1124** [MouseLand/facemap#136]
thanks for your help.  i downloaded the neural data which you answered before . it seems the data couldnt be loaded into the face map
<img width="728" alt="截屏2023-12-01 12 22 30" src="https://github.com/MouseLand/facemap/assets/152392922/b934b033-5037-4b53-904b-b3d91cb90af8">
<img width="1135" alt="截屏2023-12-01 12 23 04" src="https://github.com/MouseLand/facemap/assets/152392922/9c0a4545-2e36-4f77-99ce-daec9a35631c">
i tried to download the numpy version to 1.16 but my Mac cant compatible to that version. currently the numpy version is the latest. Anther trouble here , i wonder the neural_data_sensorimotor.zip contains the .npz,and i transform it to .npy loaded to the facemap, no matter the one-dimensional array and two-dimensional array ,it just dont work. i think the trouble is somewhere in the code need to set "data = np.load(file_path, allow_pickle=True)"
<img width="594" alt="截屏2023-12-01 12 45 54" src="https://github.com/MouseLand/facemap/assets/152392922/c155f8a9-34ee-4cc0-8b2b-16e2f5407254">
<img width="1232" alt="截屏2023-12-01 12 46 41" src="https://github.com/MouseLand/facemap/assets/152392922/f12cb274-d0c3-445a-878a-2084e6992293">
<img width="1232" alt="截屏2023-12-01 12 47 51" src="https://github.com/MouseLand/facemap/assets/152392922/246a3fd4-1b9e-4506-9cf5-5051e5ed8e3f">

**Comment by Atika-Syeda** [comment]
Hi @aubrey1124, the files downloaded contain a dictionary with different variables:
`neural_activity_*.zip: contains npz files with deconvolved neural traces "spks" (neurons by times), neuron positions "xpos" and "ypos", camera timestamps "tcam", neural timestamps "tneural", and running speed "run"`
You'll need to save the 'spks' variable in a separate .npy file to load it in the GUI (same goes for timestamp variables). You'll also have to download the face videos to generate keypoints during the neural prediction. Please let me know if you have any questions or help with saving the variables separately.
