### ISSUE TITLE
FEATURE: GPU enablement in Python API

### ISSUE THREAD

**Issue by jeremyschroeter** [MouseLand/facemap#137]
### Feature you'd like to see:

Hi I am trying to use Python to compute the motSVD and movSVD of several videos. I would like to use the GPU but don't see an option to enable this via the API, only by opening the GUI.

**Comment by Atika-Syeda** [comment]
Hi @jeremyschroeter, the software currently doesn't use GPU for SVD processing either on GUI or via the API because it has been implemented using scikit-learn. GPU is only used during pose estimation and neural activity prediction.
