### ISSUE TITLE
Data confusion

### ISSUE THREAD

**Issue by aubrey1124** [MouseLand/facemap#138]
### Issue with current documentation:

sorry to bother, i download the data you mentioned , and i have several questions here. hoping you could help me with it.
  First,i dont know what the key 'run' stands for? is it the mice runing speed on the ball or the neuron trace?
  Second, in the beh.npy the first column which accoring to the beh_name is the running ,and it seems to be all zero?

<img width="682" alt="截屏2024-01-16 19 47 28" src="https://github.com/MouseLand/facemap/assets/152392922/a35d0c71-8ace-4d32-ac95-465628fdc4fc">

**Comment by carsen-stringer** [comment]
Hi Aubrey, it looks like you are using the single mouse processed data we
shared with the rastermap paper and this tutorial, which explains the
variables: https://github.com/MouseLand/course-materials. Please check out
the figshare with all the data for the facemap paper:
https://janelia.figshare.com/articles/dataset/Facemap_a_framework_for_modeling_neural_activity_based_on_orofacial_tracking/23712957
