### ISSUE TITLE
Regarding Movtion SVD Computation

### ISSUE THREAD

**Issue by wenxuanliang** [MouseLand/facemap#14]
Hi, in your Science paper, it is said: 
_We then compute the spatial projections of the segment onto these components, U_i=M_i*V_i. Each matrix U_i consists of the left singular vectors of M_i, scaled by the singular values and is thus a 200-dimensional summary of the segment M_i, related via an orthogonal projection._

In the _README.md_, the (pseudo-) code reads:

uMot = [];
```
for j = 1:nchunks
  M = abs(diff(F,1,2));
  [u,~,~] = svd(M - avgmot);
  uMot = cat(2, uMot, u);
end
[uMot,~,~] = svd(uMot);
uMotMask = normc(uMot(:, 1:500)); % keep 500 components
```

And also in the function _computeSVDmotion.m_, line 95-97 reads
```
            [u s v] = svdecon(imot);
            u       = gather_try(u);
            uMot{z}    = cat(2, uMot{z}, u(:,1:min(200,size(u,2))));
```
So the latter two cases, the singlar values seem to be discarded. Does this actually not matter, or is this some updated calculation method? I am confused.
Thank you!

**Comment by carsen-stringer** [comment]
Sorry about this! You and the paper are correct, you should keep the singular values to get a better estimate of the true principal components. In practice I didn't see a huge difference, but I will add this back into the code base.

**Comment by carsen-stringer** [comment]
(this behavior was indeed present in the original version of facemap that we used in the paper, and if you want to use it I put it [here](https://github.com/carsen-stringer/FaceMapOriginal))

**Comment by wenxuanliang** [comment]
Hi Dr. Stringer, thank you a lot for the clarification! Glad to know that there is no much difference. 
Sorry for my delayed follow-up.
