### ISSUE TITLE
FEATURE: multiple paw keypoints

### ISSUE THREAD

**Issue by phanhuynh** [MouseLand/facemap#140]
### Feature you'd like to see:

Hello and thank you so much for this tool!  
For keypoints traces, would it be possible to have more than one keypoint for paws?  If I have a video showing 3 paws of one mouse, can I load the same video 3 times and use finetune to identify a different paw in each video?  
(Clearly, I'm new to Facemap :) )
Thank you again! 
![image](https://github.com/MouseLand/facemap/assets/54812682/091ff8c3-30eb-4afd-8ece-ae3a3ddfd9b7)

**Comment by Atika-Syeda** [comment]
Hi @phanhuynh, currently Facemap is set to track fixed number of keypoints and there's no option to add a keypoint. This might change in a future release but for now like you said you can try building three different fine-tuned models to track each paw. Hope that helps!

**Comment by carsen-stringer** [comment]
An alternative to training 3 models is to take other keypoints you aren't using and use them as paw keypoints. You could for example take the nosebridge keypoint and another nose point (if you're not using it) and retrain them to track the other paws, so you have a single model that you run on your video once.

The neural network has a convolutional output layer with 15 outputs, and this layer is not grouped in any way by the keypoint types, so there is no special treatment for example for nose keypoints, and so solving the problem in this way should be fine. The only thing it would affect is visualizing it in the GUI (they will be colored then like nose keypoints). If this approach doesn't work, please try training the three models.

**Comment by phanhuynh** [comment]
Hello,
I hope you've been well.

So, I followed your instructions.  Unfortunately, I'm getting this error
message:

Processing video:
C:/Users/huynh/temp_local/carmen_feb/carmen_feb_FM_v5/carmen_feb_VIDEO_SHORT.avi
Using params:
        bbox: [0, 562, 0, 936]
        batch size: 4
        resize: True
        padding: True
Inference speed: 6.829102724539109 fps
Saved keypoints:
C:/Users/huynh/temp_local/carmen_feb/carmen_feb_FM_v5\carmen_feb_VIDEO_SHORT_FacemapPose.h5
Saved metadata:
C:/Users/huynh/temp_local/carmen_feb/carmen_feb_FM_v5\carmen_feb_VIDEO_SHORT_FacemapPose_metadata.pkl
Loading keypoints:
C:/Users/huynh/temp_local/carmen_feb/carmen_feb_FM_v5\carmen_feb_VIDEO_SHORT_FacemapPose.h5
Loading keypoints:
C:/Users/huynh/temp_local/carmen_feb/carmen_feb_FM_v5\carmen_feb_VIDEO_SHORT_FacemapPose.h5
Traceback (most recent call last):
  File
"C:\Users\huynh\AppData\Local\anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py",
line 1300, in process_ROIs
    self.pose_model.plot_pose_estimates()
  File
"C:\Users\huynh\AppData\Local\anaconda3\envs\facemap\lib\site-packages\facemap\pose\pose.py",
line 525, in plot_pose_estimates
    self.gui.load_keypoints()
  File
"C:\Users\huynh\AppData\Local\anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py",
line 1516, in load_keypoints
    self.pose_x_coord.append(pose_data[bodypart]["x"][:])
AttributeError: 'numpy.ndarray' object has no attribute 'append'
Traceback (most recent call last):
  File
"C:\Users\huynh\AppData\Local\anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py",
line 1138, in start
    self.update_pose()
  File
"C:\Users\huynh\AppData\Local\anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py",
line 1566, in update_pose
    self.pose_likelihood[video_id][:, self.cframe]
IndexError: index 1 is out of bounds for axis 0 with size 1
Traceback (most recent call last):
  File
"C:\Users\huynh\AppData\Local\anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py",
line 1113, in next_frame
    self.update_pose()
  File
"C:\Users\huynh\AppData\Local\anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py",
line 1566, in update_pose
    self.pose_likelihood[video_id][:, self.cframe]
IndexError: index 1 is out of bounds for axis 0 with size 1
Traceback (most recent call last):
  File
"C:\Users\huynh\AppData\Local\anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py",
line 1113, in next_frame
    self.update_pose()
  File
"C:\Users\huynh\AppData\Local\anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py",
line 1566, in update_pose
    self.pose_likelihood[video_id][:, self.cframe]
IndexError: index 1 is out of bounds for axis 0 with size 1
Traceback (most recent call last):
  File
"C:\Users\huynh\AppData\Local\anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py",
line 1113, in next_frame
    self.update_pose()
  File
"C:\Users\huynh\AppData\Local\anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py",
line 1566, in update_pose
    self.pose_likelihood[video_id][:, self.cframe]
IndexError: index 1 is out of bounds for axis 0 with size 1
