### ISSUE TITLE
Pupil SVD Use Case for Just Pupil Data

### ISSUE THREAD

**Issue by KemalOz21** [MouseLand/facemap#148]
To whom it may concern,
First of all, congratulations on publishing and developing Facemap AI. The paper was intriguing for me to read. I currently have mouse pupillometry data and I want to use Facemap's pupil SVD option to find the spatially and temporally changing pupil area. Can the program work for just a pupil video, or does it need to have the whole mouse's face as shown in the pupil SVD documentation?

Thanks

**Comment by carsen-stringer** [comment]
Hi @KemalOz21 , you can track the pupil with facemap without a full video -- you will want to draw the ROI for the pupil just around the eye anyway. This video is a bit out-dated but the ROIs work the same way in the latest version: https://www.youtube.com/watch?v=Rq8fEQ-DOm4

**Comment by KemalOz21** [comment]
Thank you so much for sharing the video. It was very helpful
