### ISSUE TITLE
How can I ensure that the pupil set in the ROI is correct?

### ISSUE THREAD

**Issue by temeritylab** [MouseLand/facemap#24]
Hello, I have been using your software for a project and I was wondering if there was a way to double check or make sure that the pupil is the only part of the ROI that is being measured? Further, how do I establish that the sigma I use is the correct one?

**Comment by Atika-Syeda** [comment]
Hi, you can try changing(decreasing) the saturation of the pupil ROI to view if any other areas are in the ROI. The value of sigma depends on your analysis and suggested to reduce the size of videos used for processing if higher resolution videos are used.
