### ISSUE TITLE
Bugs in latest version

### ISSUE THREAD

**Issue by alex-attinger** [MouseLand/facemap#25]
First of all, thank you so much for making this tool available! 
I updated to the latest github repository and I think there might be a couple of bugs. 

1) when I save ROI's from multiple (consecutive) files and then hit process batch, the output of the batch process is saved in the current working directory, instead of the video folder. I think this is because in the .proc files that are generated, proc['save_path'] is an empty string. This empty string gets then set as basename.[https://github.com/MouseLand/facemap/blob/460bf1b220b3acef32a1224262d3fd17f549e102/facemap/process.py#L355](url) It is only an issue when batch processing. 

2) In some update in the past, you stopped computing iframes [https://github.com/MouseLand/facemap/blob/460bf1b220b3acef32a1224262d3fd17f549e102/facemap/io.py#L208](url) . This leads to an error here: [https://github.com/MouseLand/facemap/blob/460bf1b220b3acef32a1224262d3fd17f549e102/facemap/gui.py#L634](url)

I hardcoded fixes for me, but you might want to look into it.

**Comment by Atika-Syeda** [comment]
Thanks for letting us know. Please pull latest changes and let us know if the problem still persists.
