### ISSUE TITLE
cannot save ROIs

### ISSUE THREAD

**Issue by vickerse1** [MouseLand/facemap#26]
When I click on the "save ROIs" button, I get the following error:

 File "/usr/local/anaconda3/envs/facemap/lib/python3.7/site-packages/facemap/gui.py", line 640, in save_ROIs
    'filenames': self.filenames, 'iframes': self.iframes}
AttributeError: 'MainW' object has no attribute 'iframes'

I am using GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu), with python 3.7.3 and anaconda 3.

Can you help me with this?

Thanks,

Evan

**Comment by Atika-Syeda** [comment]
Thanks for reaching out. Please pull latest changes for the bug fix.

**Comment by vickerse1** [comment]
Hi Atika-Syeda,

There seems to be a version control problem in gui.py. Could you please send me an environment.yml from a known working install?

Thanks,

Evan

**Comment by Atika-Syeda** [comment]
Hi Evan,

You can now download the updated environment.yml file from main.
