### ISSUE TITLE
video formating related issues

### ISSUE THREAD

**Issue by juplab** [MouseLand/facemap#4]
file to replicate the error can be found on https://drive.google.com/drive/folders/13yguLJ50IOWR06xsxyNTybt6AfC2QOEw?usp=sharing [https://drive.google.com/drive/folders/13yguLJ50IOWR06xsxyNTybt6AfC2QOEw?usp=sharing](url)

Thanks a lot for creating this very useful software! I am currently struggling on implementation of the software for a specific set of video which I think is due to formating. Any advice or feedback would be welcome. Currently Facemap works in those video if they are refinished with ffmpeg and compressed see file 1571Comp.mp4 in addition in 

projectMasks.m, line 7:
nframes = h.nframes; was replaced by nframes = int64(h.nframes);

**_WINDOWS7 Matlab2018a_**
**ERROR1**
file:
1571#_refinish.mp4
   2.4350e+03

Error using PlotFrame (line 16)
No more frames available to read from file.

Error in MovieGUI>folder_Callback (line 215)
        PlotFrame(h);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in MovieGUI (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)MovieGUI('folder_Callback',hObject,eventdata,guidata(hObject))
 
Error using uiwait (line 81)
Error while evaluating UIControl Callback.

Index exceeds array bounds.

Error in onScreenROI (line 4)
roi0(1) = min(nX,max(1,ROI(1)));

Error in MovieGUI>keepROI_Callback (line 262)
ROI = onScreenROI(ROI, nxS, nyS);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in MovieGUI (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)MovieGUI('keepROI_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback.

**ERROR2**
file: 1571#_refinish.mp4
Error using VideoReader/init (line 601)
Could not read file due to an unexpected error. Reason: Error Creating Source Reader Reason: Unknown error 0xC00D36C4

Error in VideoReader (line 171)
            obj.init(fileName);

Error in MovieGUI>folder_Callback (line 157)
                h.vr{k,j} = VideoReader(filename{k,j});

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in MovieGUI (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)MovieGUI('folder_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback.

Index exceeds array bounds.

Error in findMovieFolders (line 18)
            namef = cat(1,namef, namef0{k});

Error in MovieGUI>folder_Callback (line 135)
    [filename,folders,namef] = findMovieFolders(h,folder_name);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in MovieGUI (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)MovieGUI('folder_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback.

**ERROR3**
video e3v818a-20180814T1133-1134_30fps_refinish.mp4 crashes Matlab

_**MAC OS Matlab2018a**_ 
**ERROR4**
video e3v818a-20180814T1133-1134_30fps_refinish.mp4 gives the following error
1 / 40 done in 1.51 sec
6 / 40 done in 8.25 sec
11 / 40 done in 15.03 sec
16 / 40 done in 21.86 sec
21 / 40 done in 28.69 sec
26 / 40 done in 35.65 sec
31 / 40 done in 42.64 sec
36 / 40 done in 49.63 sec
Error using subsampledMean (line 68)
No more frames available to read from file.

Error in processROIs (line 9)
h = subsampledMean(h);

Error in MovieGUI>processROIs_Callback (line 429)
h = processROIs(h);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in MovieGUI (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)MovieGUI('processROIs_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback.

**Comment by carsen-stringer** [comment]
I'm not getting any of the video codec errors that you're getting (I'm running Matlab 2018a on Ubuntu 18.04). But there were plenty of bugs because your video length * frame rate is not an integer (which I haven't seen before - maybe associated with matlab misreading the files?). Some of the other bugs in the pipeline were because your videos are very short.

I've fixed any bugs in the pipeline that were associated with those issues by testing:
1571#.mp4 (It thinks there are 2434 frames is that right?)
1571#_refinish.mp4 (It thinks there are 2434 frames is that right?)
1571Comp.mp4 (It thinks there are 2435 frames is that right?)
e3v..._30fps.mp4 (It thinks there are 60 frames is that right?)
e3v..._30fps_refinish.mp4 (It thinks there are 2011 frames is that right?)

Are you planning on running on a bunch of short movies in a row? I stitch together the movies if you have multiple to run in a row, and I'm a little worried that these non-integer frames might be a problem.

**Comment by juplab** [comment]
Thanks for the quick reply. In the projectMasks.m, line 7:
nframes = h.nframes; was replaced by nframes = int64(h.nframes); which is taking care of the non integer situation. We will run longer video. I will look into the codecs in more details thanks again for your help.
