### ISSUE TITLE
Could you please provide the sample video？ 

### ISSUE THREAD

**Issue by hjwq** [MouseLand/facemap#43]
Hi! I want to try this useful tools before the experiment began, so Could you please provide some sample video？ 

thank you!

**Comment by Atika-Syeda** [comment]
Hello, 

please find sample videos here: https://drive.google.com/drive/folders/1cRWCDl8jxWToz50dCX1Op-dHcAC-ttto

**Comment by msarvestani** [comment]
Would it be possible to also share some sample neural data, and the .npy files for neural and behavioral timestamps that go with the sample videos? I'm having some issues with neural prediction that very likely have to do with data formatting on my end and this would help me resolve them. Thank you.
