### ISSUE TITLE
Unable to open GUI  

### ISSUE THREAD

**Issue by hjwq** [MouseLand/facemap#46]
hi~ I tried to install the new tracking version
the code I ran is there:
`conda env create -f environment.yml`
`pip install git+https://github.com/mouseland/facemap.git`

but 
`ModuleNotFoundError: No module named 'facemap.gui'`

**Comment by Atika-Syeda** [comment]
Hello @hjwq, thanks for reporting the error. Please use the following instructions for setting up tracker version until we've fixed the error:

1. `git clone https://github.com/MouseLand/facemap.git`
2. Change directory to facemap folder containing environment.yml
3. `conda env create -f environment.yml`
4. `conda activate facemap`
5. `python -m facemap`

**Comment by hjwq** [comment]
> 

` No module named facemap`

**Comment by hjwq** [comment]
> Hello @hjwq, thanks for reporting the error. Please use the following instructions for setting up tracker version until we've fixed the error:
> 
> 1. `git clone https://github.com/MouseLand/facemap.git`
> 2. Change directory to facemap folder containing environment.yml
> 3. `conda env create -f environment.yml`
> 4. `conda activate facemap`
> 5. `python -m facemap`

after that ` No module named facemap`

**Comment by Atika-Syeda** [comment]
Could you please share your terminal output. I'm guessing the error is due to not running the command `python -m facemap` in the facemap directory.

**Comment by hjwq** [comment]
> python -m facemap

there I already has SVD version facemap installed，so I change the name of envs to facemap1

`(facemap1) C:\Users\25230\Downloads>python -m facemap
D:\anaconda\envs\facemap1\python.exe: No module named facemap`

**Comment by hjwq** [comment]
> Could you please share your terminal output. I'm guessing the error is due to not running the command `python -m facemap` in the facemap directory.

![1](https://user-images.githubusercontent.com/100213882/159478387-359892bd-b505-4e94-ad72-e00f644ead1e.png)
![2](https://user-images.githubusercontent.com/100213882/159478502-fe3810ba-85c4-4022-92fb-63d3c0bac7fb.JPG)

there I already has SVD version facemap installed，so I change the name of envs to facemap1
`(facemap1) C:\Users\25230\Downloads>python -m facemap`
`D:\anaconda\envs\facemap1\python.exe: No module named facemap`

**Comment by hjwq** [comment]
> Could you please share your terminal output. I'm guessing the error is due to not running the command `python -m facemap` in the facemap directory.

or you mean I should download all code from git?

**Comment by Atika-Syeda** [comment]
Please make sure you have changed your current directory to facemap when running `python -m facemap`. Currently, it shows you are in the Downloads folder. 
Also, the tracker version contains SVD processing as well so you can use the same environment and package.

**Comment by hjwq** [comment]
> 1. git clone https://github.com/MouseLand/facemap.git


![image](https://user-images.githubusercontent.com/100213882/159611246-8ac97960-c0cd-4307-ad71-b3b83cf98d35.png)

**Comment by Atika-Syeda** [comment]
Please see https://github.com/MouseLand/facemap/issues/47#issuecomment-1075132228
