### ISSUE TITLE
svd computation error w/ higher sbin values

### ISSUE THREAD

**Issue by richardjburman** [MouseLand/facemap#47]
Followed the installation instructions and managed to launch the GUI, but it appeared incomplete complared to Git page. Cloned the repository and launch from there to get a slightly better version: 
 
![Image1](https://user-images.githubusercontent.com/50410029/159372418-e4495d56-054d-4274-be0e-d863c73fb1ba.PNG)

The GUI is very buggy and I cannot process the ROIs. 

Have checked this on Windows, Mac and Linux and have the same result.

**Comment by richardjburman** [comment]
Also worth noting that the GUI freezes if you touch the 'process batch' button, it does not save ROIs and creates empty .mat and .npy files

**Comment by Atika-Syeda** [comment]
Hello @richardjburman, it seems like the issue might be related to other problems because the error is not reproducible on our end. Could you please share any error/warning messages received during your installation and also share details of the video and ROI processing steps you used.

**Comment by richardjburman** [comment]
Hi @Atika-Syeda ,
Thank you for your prompt response.
I have reproduced the same error on two machines myself (Windows and Mac) and also asked a colleague to try on their Linux machine. In all three cases we got the same issue Below is a sequence detailing where I am with the issue:

1) Pip list within the Facemap virtual environment as installed on my PC (same as Mac and Linux)

![pip_list_1](https://user-images.githubusercontent.com/50410029/159439372-55923996-d5b8-4a31-91c1-65ee410e841d.PNG)

![pip_list_2](https://user-images.githubusercontent.com/50410029/159439412-1999fef7-93d7-48bd-a572-7acb889f8cce.PNG)

2) Taken after launching Facemap

![launch](https://user-images.githubusercontent.com/50410029/159439464-69c0dcbc-ffe1-42bd-87c5-56d5b9c87eee.PNG)

3) Taken after loading video (.avi - have also tried .mp4 and got the same issue)

![loaded_video](https://user-images.githubusercontent.com/50410029/159439608-233886b0-8efc-43e1-8f4e-b7ec70cd1499.PNG)

4) Taken after setting ROIs

![setting_roi](https://user-images.githubusercontent.com/50410029/159439628-640b24d9-56e1-48b4-b01d-336662db1c6d.PNG)

5) Taken after clicking the 'process' button

![after_processing](https://user-images.githubusercontent.com/50410029/159439731-c9ee4a2c-c4d5-45a6-88e1-0df76d35b647.PNG)

It generates .npy and .mat files (cannot upload here) which either do not load into Facemap (.npy) or appear empty (.mat). No change in terminal (see image below) after trying to load in .npy file. 

![after_loaded](https://user-images.githubusercontent.com/50410029/159439942-20dcb2f8-3c31-43be-88e6-c7004dd7ab50.PNG)

**Comment by Atika-Syeda** [comment]
Hello @richardjburman, thanks for sharing the steps in details as it helped identify the issue. It seems like SVD computation wasn't compatible for higher sbin values as shown from your terminal output. Please reinstall the updated version on main branch and try re-running the video. Please let me know if you run into an issue again.

Secondly, the GUI features are the same as displayed on our readme. The GUI looks different due to usage on Window's platform, whereas we used Mac as our platform for the GUI shown in readme.

**Comment by richardjburman** [comment]
Hi @Atika-Syeda 
Did that but now the GUI will not load at all. 
Getting this error: 
![image](https://user-images.githubusercontent.com/50410029/159476199-76bb02f1-4830-4c99-bb22-d40837fa8d1f.png)

**Comment by Atika-Syeda** [comment]
It looks like the pyqt version in the environment is incorrect. If you could please check whether your pip list returns the following version(s):
PyQt5                  5.15.6
PyQt5-Qt5              5.15.2
PyQt5-sip              12.9.1
PyQtChart              5.12
pyqtgraph              0.12.0

**Comment by richardjburman** [comment]
Thanks. 
Went through these steps again:
"
    git clone https://github.com/MouseLand/facemap.git
    Change directory to facemap folder containing environment.yml file
    conda env create -f environment.yml
    conda activate facemap
    python -m facemap This will install the latest development version on github.
"

Now working!

![image](https://user-images.githubusercontent.com/50410029/159519582-1a6fc09f-cf80-4d19-993c-e58cfb68517f.png)

Unfortunately getting an error when I try to use the Keypoints feature: 

![image](https://user-images.githubusercontent.com/50410029/159520365-44e7eb6a-eeec-4f73-b4b9-34cb52e10a95.png)

**Comment by Atika-Syeda** [comment]
Could you please run the following and share the output to check package versions:
1. `condo activate facemap`
2. `python`
3. print("python version:", python_version())
4. print("torch version:", torch.__version__) # torch version
5. print('numpy version: %s'%np.__version__)

**Comment by richardjburman** [comment]
Had to adapt a bit: 

![image](https://user-images.githubusercontent.com/50410029/159578293-ce8e472a-434d-44ec-8c9f-aa27dfd2304b.png)

**Comment by Atika-Syeda** [comment]
The issue is not related to Facemap but numpy installation/version. Please try `pip install numpy --upgrade` in the virtual environment.

**Comment by richardjburman** [comment]
Have done, but now have this error: 

![image](https://user-images.githubusercontent.com/50410029/159802772-e9b356d3-e84b-46ab-b49c-f6828c704645.png)

**Comment by Atika-Syeda** [comment]
Please make sure the following package versions are installed in the virtual environment:
~~~
numpy 0.53.1
numexpr 2.7.3
numpy 1.22.2
torch 1.11.0
~~~
To upgrade any of the above packages please use conda.
Please see https://numba.pydata.org/numba-doc/latest/user/installing.html and https://numpy.org/install/

**Comment by EstherXSD** [comment]
Hi @Atika-Syeda,

I've got exactly the same problems with @richardjburman. Specifically, first I came across with the "RuntimeError: Numpy is not available", and then I tried to upgrade the numpy version to the latest one, it told me it doesn't need that advanced NumPy version.....

By the way, my "pip list" information is as the following:
`Package                Version
---------------------- ---------
certifi                2021.10.8
charset-normalizer     2.0.12
colorama               0.4.4
cycler                 0.11.0
facemap                0.2.0
fonttools              4.31.2
hdbscan                0.8.28
idna                   3.3
joblib                 1.1.0
kiwisolver             1.4.0
llvmlite               0.38.0
matplotlib             3.5.1
natsort                8.1.0
numba                  0.55.1
numexpr                2.7.3
numpy                  1.21.5
opencv-python-headless 4.5.5.64
packaging              21.3
pandas                 1.4.1
Pillow                 9.0.1
pip                    22.0.4
pynndescent            0.5.6
pyparsing              3.0.7
PyQt5                  5.15.6
PyQt5-Qt5              5.15.2
PyQt5-sip              12.9.1
PyQtChart              5.12
pyqtgraph              0.12.0
PyQtWebEngine          5.12.1
python-dateutil        2.8.2
pytz                   2022.1
requests               2.27.1
scikit-learn           1.0.2
scipy                  1.8.0
setuptools             60.10.0
six                    1.16.0
tables                 3.7.0
threadpoolctl          3.1.0
torch                  1.11.0
torchvision            0.12.0
tqdm                   4.63.1
typing_extensions      4.1.1
umap-learn             0.5.2
urllib3                1.26.9
wheel                  0.37.1`

Eager to know whether @richardjburman has solved the problem by installing right package versions as the last message suggests.

**Comment by t-chari** [comment]
Hi, was this issue ever solved? Also having the same problem here and tried upgrading numpy but it didn't seem to resolve the issue.

Here are all the versions for the packages:

certifi                2021.10.8
charset-normalizer     2.0.12
colorama               0.4.4
cycler                 0.11.0
Cython                 0.29.28
fonttools              4.33.3
hdbscan                0.8.28
idna                   3.3
joblib                 1.1.0
kiwisolver             1.4.2
llvmlite               0.38.0
matplotlib             3.5.1
natsort                8.1.0
numba                  0.55.1
numexpr                2.7.3
numpy                  1.21.6
opencv-python-headless 4.5.5.64
packaging              21.3
pandas                 1.4.2
Pillow                 9.1.0
pip                    22.0.4
pynndescent            0.5.6
pyparsing              3.0.8
PyQt5                  5.15.6
PyQt5-Qt5              5.15.2
PyQt5-sip              12.10.1
PyQtChart              5.12
pyqtgraph              0.12.0
PyQtWebEngine          5.12.1
python-dateutil        2.8.2
pytz                   2022.1
requests               2.27.1
scikit-learn           1.0.2
scipy                  1.8.0
setuptools             62.1.0
six                    1.16.0
tables                 3.7.0
threadpoolctl          3.1.0
torch                  1.11.0
torchvision            0.12.0
tqdm                   4.64.0
typing_extensions      4.2.0
umap-learn             0.5.3
urllib3                1.26.9
wheel                  0.37.1

Thanks!

**Comment by Atika-Syeda** [comment]
Hi  @EstherXSD and @t-chari, please open a new issue with description of the error and the steps.
