### ISSUE TITLE
unregistered movSv and motSv values

### ISSUE THREAD

**Issue by tdincer** [MouseLand/facemap#50]
movSv and motSv are not updated in the proc file after the SVD computation process - so they are always zero arrays. This happens when the computation is done via the command line without the GUI object in the following way:

```python
import numpy as np
from facemap.process import run

videofiles = [['video.avi']]
proc = np.load('video_proc.avi', allow_pickle=True).item()
output_path = './user/test_folder'
run(videofiles, sbin=proc['sbin'], proc=proc, savepath=output_path, motSVD=proc['motSVD'], movSVD=proc['movSVD'])
```

**Comment by Atika-Syeda** [comment]
Hello @tdincer, can you please check if proc["fullSVD"]=True? If you're passing proc as an input then you don't need to set sbin. Plus, proc["motSVD"] and proc["movSVD"] would contain list/array as it would be the output from running svd whereas the run command takes bool as input i.e. motSVD=True/False to check whether to run motSVD similar to movSVD.
