### ISSUE TITLE
Using more than one 'Running' ROI

### ISSUE THREAD

**Issue by Dbrown-neuro** [MouseLand/facemap#52]
Hello,

We would like to use multiple Running ROIs, to capture movement in multiple areas of the video.

Whenever we try to use more than one Running ROI, we receive the following:
`Error: File "...miniconda3/envs/facemap/lib/python3.7/site-packages/facemap/process.py", line 285, in process_ROIs
    imr = np.concatenate((rend[k][np.newaxis,:,:],imr), axis=0)
IndexError: list index out of range`

I noticed that other ROI types (for ex. 'Blink') allows more than one ROI to be drawn.  Should we be able to use multiple Running ROIs, as well?

Thank you in advance for your help,
Daniel

**Comment by Atika-Syeda** [comment]
Hi, please check our latest version for multiple ROIs.
