### ISSUE TITLE
Failed to initialize NumPy on Windows 10

### ISSUE THREAD

**Issue by aeronlaffere** [MouseLand/facemap#55]
When running `python -m facemap` I see the following warning:

`> python -m facemap
...\mambaforge\envs\facemap\lib\site-packages\torch\_masked\_init_.py:223: UserWarning: Failed to initialize NumPy: module compiled against API version 0xf but this version of numpy is 0xe (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  example_input = torch.tensor([[-3, -2, -1], [0, 1, 2]])
numpy version: 1.21.6 
python version: 3.10.4`

Subsequently, facemap fails to process videos because of a failure to initialise numpy. 

Searching for a fix to this error, I have found generic advice to simply upgrade to the latest version of numpy. This appears to not apply here since we are constrained to numpy < 1.22 by numba.

**Comment by Atika-Syeda** [comment]
Hello,
Can you please create a conda environment with python version 3.9 and share versions of the installed packages from your `pip list` output.

**Comment by aeronlaffere** [comment]
I created a new environment with `conda create --name test python=3.9` then ran `pip list` which gave the following output:

`Package      Version
------------ ---------
certifi      2021.10.8
pip          21.2.4
setuptools   61.2.0
wheel        0.37.1
wincertstore 0.2`

**Comment by Atika-Syeda** [comment]
Sorry for the unclear instructions. Basically, you want to use [facemap's conda environment](https://github.com/MouseLand/facemap/blob/main/environment.yml) with python version 3.9. Please let me know if that still leads to the error above.

**Comment by Atika-Syeda** [comment]
Alternatively, you can create a clean environment (like above) then install facemap packages there
