### ISSUE TITLE
Movement energy calculation/intuition

### ISSUE THREAD

**Issue by tharmon0118** [MouseLand/facemap#58]
Hello,

Thanks for developing this tool! It's made a huge difference for me in my research.

I'd like to compare motion energies from videos collected from different experiments. The POV is very similar between videos but the exact lighting conditions and ROI dimensions may be slightly different. I've been normalizing the movement energy values by z scoring, but this is problematic because the animals move different amounts in different videos. Would you expect the motion energy values to be comparable between videos like these? If not, any advice you could give about normalizing would be appreciated. 

Thank you,
Tom Harmon

**Comment by Atika-Syeda** [comment]
Hi @tharmon0118, the motion energy only computes the average of the absolute value of the difference between frames (pixel values). Hence, the values can vary depending on the videos and would make comparison across different experiments unreliable if the conditions are variable. If you wish to compare movement of animals across different experiments, I'd suggest using pose estimation to track specific keypoints and subsequently using them for comparison.
