### ISSUE TITLE
Expired Certificate (GUI in Ananconda)

### ISSUE THREAD

**Issue by Zywderek** [MouseLand/facemap#59]
I have been trying to use facemap GUI in Anaconda virtual environment. 

Every time I press "PROCESS'' in the GUI panel, it shows certificate expiry information (an example snapshot is attached below). So I'm wondering do you have any suggestions on this issue.

![Screenshot Facemap Error Message.png](https://user-images.githubusercontent.com/89178794/182663475-8882696b-8e2a-4840-a675-e0a1e3c9527d.png)

Thanks a lot for all your support and patience.

**Comment by Atika-Syeda** [comment]
Hello @Zywderek, we'll look into fixing the issue in the new release. Meanwhile, you can try adding this https://github.com/MouseLand/cellpose/issues/346#issuecomment-962642395 after the import statements in this file: https://github.com/MouseLand/facemap/blob/main/facemap/pose/models.py
Let me know if it doesn't resolve the error.
