### ISSUE TITLE
Reshape error in Python compute_SVD

### ISSUE THREAD

**Issue by obarnstedt** [MouseLand/FaceMap#6]
Hi,
recently I've been getting a reshape error every time I try to run the Python GUI. It looks like this:
`processing videos
computed subsampled mean at 17.10s
Traceback (most recent call last):
  File "/Users/Oliver/FaceMap/FaceMap/gui.py", line 521, in process_ROIs
    self.motSVDs, self.pupils = facemap.run(self.filenames, self)
  File "/Users/Oliver/FaceMap/FaceMap/facemap.py", line 50, in run
    U = compute_SVD(video, cumframes, avgmotion, ncomps, sbin, rois)
  File "/Users/Oliver/FaceMap/FaceMap/facemap.py", line 185, in compute_SVD
    imbin = np.reshape((Lyb, Lxb, -1))
TypeError: reshape() missing 1 required positional argument: 'newshape'
Abort trap: 6`
This occurs after pressing 'processing' of 4 motion SVD ROIs, 1 blink ROI, and 1 pupil ROI (sigma 1.8).

EDIT: I should add that this exclusively occurs when selecting motion SVD ROIs. Selecting only a pupil ROI does not cause any problems, but one single motion SVD ROI causes the same problem.

**Comment by carsen-stringer** [comment]
Sorry about that I've fixed this issue

In terms of the pupil, make sure to set the saturation really high to avoid the eyelid. you can also try turning off the smoothing in X and Y line 77 in roi.py for plotting and line 45 in pupil.py . I've also seen deeplabcut with pupils look good, but I'm not sure how much training data you need.

I will add an issue for the polygon enhancement

**Comment by carsen-stringer** [comment]
also the blink isn't implemented yet

**Comment by carsen-stringer** [comment]
there were some bugs in the pupil ROI plotting -- things might look better now. I've also added multivideo support (see the readme for more info)

**Comment by obarnstedt** [comment]
Thanks a lot, Carsen! Working fine now!
