### ISSUE TITLE
Artifacts in the motion output variable

### ISSUE THREAD

**Issue by ngf7** [MouseLand/facemap#60]
Hello, 
When plotting the output data after calculating motSVD and movSVD we noticed that the motion_1 matrix has abnormal peaks in the data exactly every 500 frames. This occurred in both the outputs of a sample movie provided on your github as well as in our own data. It would be greatly appreciated if you could let us know what these peaks represent, and how these artifacts influence the motSVD calculations because they are also present in at least the first dimension of the motSVD. 

Sample movie motion_1
![motion_1 plot](https://user-images.githubusercontent.com/58956003/191038793-36207647-b709-4181-b8f6-64d934759647.jpg)

Our data motion_1 
![motion_1 ourdata plot](https://user-images.githubusercontent.com/58956003/191038828-6be1e1ea-59d6-4a6c-a3ce-2cbb2e6b99f7.jpg)

Sample data motSVD (first dimension only)
![motSVD sample](https://user-images.githubusercontent.com/58956003/191038886-ca510266-cc39-4787-8ecc-ab618ecb36a8.jpg)

Our data motSVD (first dimension only)
![motSVD ourdata](https://user-images.githubusercontent.com/58956003/191038909-d38908df-238c-4d41-bdd8-91d38dd9295e.jpg)

**Comment by Atika-Syeda** [comment]
Hello,
Can you please share which version of facemap you are running? Please install the current version on the main branch.

**Comment by ngf7** [comment]
Hi,
We are using the latest version of facemap initially installed from the Github about two weeks ago.

**Comment by ngf7** [comment]
Also we are using the python GUI, the plots were generated in Matlab after the data was processed.

**Comment by Atika-Syeda** [comment]
Can you please try using the pip version through "pip install facemap==0.2.0" while we look into the issue. Thanks!

**Comment by magdalenasabat** [comment]
Hi! Similar issue here.

`np.diff(np.where(vid['motSVD'][0][:,i] < -2000))`

```
array([[14500, 15000, 14500, 15000, 14500, 15000, 14500, 15000, 14500,
        15000, 14500, 15000, 14500, 15000, 14500, 15000, 14500, 15000,
        14500, 15000, 15000, 15000, 15000, 15000, 15000, 15000, 15000,
        15000, 15000, 15000, 15000, 15000, 15000, 15000, 15000, 15000,
        15000, 15000, 15000, 15000, 15000, 15000, 15000, 15000, 15000,
        15000, 15000, 15000, 15000, 15000, 15000, 15000, 15000, 15000,
        45000]])
```

python=3.8 
facemap==1.0.0

also, 'motion' returns an array of length of frames with identical value at every frame. 

Ubuntu 20.04

**Comment by Atika-Syeda** [comment]
Hi @magdalenasabat do you still see the same artifact in the latest version?

**Comment by magdalenasabat** [comment]
Hi! nope, but from what i remember this was again a problem with number of frames property read from the video .
