### ISSUE TITLE
FaceMap freezes when batch running

### ISSUE THREAD

**Issue by camille-lab** [MouseLand/facemap#61]
Hi, 
I am experiencing an bug when I try to batch run FaceMap from the GUI.
It works on the 1st session but then freezes for the 2nd, with FaceMap trying to load a model....(see picture attached).

thanks for your help!
![FaceMap_Freezing](https://user-images.githubusercontent.com/53828465/192302693-d0647443-e8f1-4979-aa63-62522bdf96b4.png)

**Comment by faezehrabbani97** [comment]
I have the same issue did you solve the problem?

![Capture d’écran 2022-10-12 164255](https://user-images.githubusercontent.com/101398285/195375176-e3b59add-8bcc-475c-b463-9e6b1aad79b9.png)

**Comment by Atika-Syeda** [comment]
Hello @camille-lab  and @faezehrabbani97, thanks for using facemap. Could you please share more details about the error? From what I can infer it seems like you are running pose estimation on cpu so it will take a while to process the videos. If you wait a little longer you'll see a progress bar indicating % of video processed if you're trying to get keypoints. Please let me know if it's a different issue.

**Comment by faezehrabbani97** [comment]
For how long we should wait? I think it takes forever. At some point, it seems the facemap gets stuck because after hours there is no progress.

**Comment by camille-lab** [comment]
Hello, I do not try to run pose estimation, only SVD
