### ISSUE TITLE
ROI not working, latest version of facemap interger issue

### ISSUE THREAD

**Issue by maylisilva** [MouseLand/facemap#65]
Dear all, thanks for all the work put here! 
I do not manage to change the position of the ROI on facemap, and even if there is no ROI everytime the mouse passes by, I get this error:
Does anybody knows how to solve it? 
Thanks!!!!

![image](https://user-images.githubusercontent.com/39194393/200827606-2dbdfef7-7bd2-4c33-a961-1414497f6614.png)

**Comment by hmacomber** [comment]
No solution here, but I've been running into a very similar issue that has the same 'argument 1 has unexpected type float' issue. Every time I try to add an ROI and manipulate it in any way in the GUI, it refuses to modify the shape/let me click on anything and instead just gives me

TypeError: setAlpha(self, int): argument 1 has unexpected type 'float'

on repeat. This wasn't an issue until the last few weeks, so I'm not sure exactly what's happened. I've attached a screenshot as well.  

<img width="802" alt="Screen Shot 2022-11-09 at 11 40 54 AM" src="https://user-images.githubusercontent.com/42822650/200901766-43fe239b-8c98-4fa4-bbcf-e767239d4964.png">

**Comment by hmacomber** [comment]
Did some troubleshooting - it looked like my environment was on pyqtgraph==0.11.0, when it needed to be on pyqtgraph==0.12.0 to prevent the error. Odd given that I installed everything from the yml and that's the current dependency, but maybe that might help you as well!

**Comment by Atika-Syeda** [comment]
thanks @hmacomber for troubleshooting and sharing the solution. @maylisilva please let me know if you're still having any trouble with the ROI setting.
