### ISSUE TITLE
Processing Error: MainW has no attribute sigmaBox

### ISSUE THREAD

**Issue by msarvestani** [MouseLand/facemap#69]
Hi,
I'm using the latest clone + environment.yml file for install, and already tried reinstalling PyQt5. I get the following error (AttributeError: 'MainW' object has no attribute 'sigmaBox')  when processing any ROI (no keypoints even).  

Thanks!

Win10, python 3.8, Nvidia GeForce GTX 1660 Ti, driver 516.4, Cuda toolkit 11.2, 

numpy version: 1.23.4
python version: 3.8.13
Running Facemap w/ pose estimation GUI
QGridLayoutEngine::addItem: Cell (2, 0) already taken
QGridLayoutEngine::addItem: Cell (3, 0) already taken
QGraphicsScene::removeItem: item 0x1b3cce378a0's scene (0x0) is different from this scene (0x1b3ccd723a0)
QGraphicsScene::removeItem: item 0x1b3cce34420's scene (0x0) is different from this scene (0x1b3ccd71a20)
Computing subsampled mean...
Computed subsampled mean at 37.62s
Computing subsampled SVD...
computed svd chunk 0 / 4, time  22.29sec
computed svd chunk 1 / 4, time  44.99sec
computed svd chunk 2 / 4, time  67.94sec
computed svd chunk 3 / 4, time  90.49sec
Computed subsampled SVD at 130.53s
Computing projection for motSVD...
computed projection chunk 0 / 9, time  140.66sec
Computed motSVD projection at 235.79s
run time 235.93s
QGraphicsScene::removeItem: item 0x1b3d5355f10's scene (0x0) is different from this scene (0x1b3ccd71a20)
QGraphicsScene::removeItem: item 0x1b3d5355f10's scene (0x0) is different from this scene (0x1b3ccd71a20)
Traceback (most recent call last):
  File "D:\Facemap\facemap\gui\gui.py", line 1230, in process_ROIs
    io.open_proc(self, file_name=savename)
  File "D:\Facemap\facemap\gui\io.py", line 182, in open_proc
    parent.sigmaBox.setText(str(roi["pupil_sigma"]))
AttributeError: 'MainW' object has no attribute 'sigmaBox'

**Comment by benefron** [comment]
I am having the same issues. Does anyone have a solution?

**Comment by orena1** [comment]
Ho, yes, I think it is related to the pyqt versions, the location of things changed in the new versions of pyqt. I manually had to change the imports. 
Look at how they did it in suite2p and cellpose, there you can see the correct way to do the imports in the new versions.
Let me know if it does not work, I can try to check what are the changes that I've made.

**Comment by Atika-Syeda** [comment]
Hi @benefron and @msarvestani, thanks for opening the issue and helping debug the code. The updated code on main branch should have resolved the problem. Please let me know if the error still persists when processing ROIs.
