### ISSUE TITLE
Gui not running 

### ISSUE THREAD

**Issue by benefron** [MouseLand/facemap#71]
Hi I followed the instruction to install facemap.
I have a new computer so I had to reinstall the software which was working well before.
I am running Ubuntu 22.04 with Nvidia GPU with cuda 12.0.
When I pip install the package in the environment I get the following:
"Warning: facemap 0.2.0 does not provide the extra 'gui'"
The installation is the successful but when trying to run "python -m facemap" I get the following:
"ModuleNotFoundError: No module named 'cv2'"

**Comment by orena1** [comment]
install opencv headless:
`pip install opencv-python-headless`

**Comment by Atika-Syeda** [comment]
Thanks @orena1 for helping resolve the issue. @benefron please let me know if you still have any trouble installing/running facemap.

**Comment by benefron** [comment]
This issue is resolved, but I have a different problem, and I commented about it here https://github.com/MouseLand/facemap/issues/69#issuecomment-1368431431
