### ISSUE TITLE
Adding options for changing image settings when annoteting

### ISSUE THREAD

**Issue by benefron** [MouseLand/facemap#75]
Hi,
Is there an option to add a feature that will allow users to change the parameters of the image when annotating just for visualization without affecting the image fed to the pose estimation model, such as gain, contrast, masks, etc.?
This will improve the annotation, and the model can run on unprocessed data.
Thanks,
Ben

**Comment by Atika-Syeda** [comment]
Hi @benefron, thanks for the suggestion. Currently, you can change the saturation of the images in the GUI. We can look into adding other settings in the future.
