### ISSUE TITLE
Finetune model not showing in pose model dropdown menu 

### ISSUE THREAD

**Issue by nelson-hc** [MouseLand/facemap#76]
Hi,

I followed the guide to create a finetune model for keypoint processing and saved it as a .pt file in an output file. However, I am not able to find any finetune models I created in the pose model drop-down menu.

**Comment by Atika-Syeda** [comment]
Hi @nelson-hc, could you please check whether the .pt file was saved in the hidden folder. You can search for it through command line as follows:
`cd /home/<username>/.facemap/models`
`ls`
Let me know if you can't find any file saved in the directory.

**Comment by nelson-hc** [comment]
Yes, they are saved in .facemap/models. I did see multiple .pt files.

**Comment by Atika-Syeda** [comment]
Could you please share screenshot of the files in the models directory and the pose model dropdown menu? Also, could you please share which OS you're using i.e. Windows, Linux..?

**Comment by nelson-hc** [comment]
I am using windows. 

![image](https://user-images.githubusercontent.com/113548755/211641372-d598731b-e8de-4169-bfc7-8b47904d1772.png)

![image](https://user-images.githubusercontent.com/113548755/211641469-f917f9aa-3b61-4436-8207-b67abe2b588a.png)

**Comment by Atika-Syeda** [comment]
thanks @nelson-hc for sharing that. It seems our code didn't account for Windows file paths so I've updated/fixed it in the main branch. Could you please pull/clone the latest version on the main branch and let me know if the problem still persists.

**Comment by nelson-hc** [comment]
The problem is resolved, thanks!!
