### ISSUE TITLE
Running Facemap w/ pose estimation GUI "Aborted"

### ISSUE THREAD

**Issue by wiesoauch** [MouseLand/facemap#79]
If the GUI is started with `$ python -m facemap` I get the following error:
```
OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
numpy version: 1.23.5
python version: 3.8.15
Running Facemap w/ pose estimation GUI
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted
```

The problem might be related to this? https://github.com/NVlabs/instant-ngp/discussions/300. However, using `opencv-python-headless 4.7.0.68` produces the same error.

`pip uninstall pyqt5 pyqt5-tools` and `pip install pyqt5 pyqt5-tools pyqt5.sip` also didn't fix the error.

I am on Devuan GNU/Linux 4 (chimaera).

**Comment by Atika-Syeda** [comment]
Hi @wiesoauch which version of facemap are you using? could you please share the output of `pip list` for your conda env?

**Comment by wiesoauch** [comment]
Hi @Atika-Syeda, I figured out the Problem. I forgot to pipe the output to a monitor from the server. I am now starting the GUI via x2go and it works. Thank you!
