### ISSUE TITLE
Value error cannot reshape array of size

### ISSUE THREAD

**Issue by juplab** [MouseLand/FaceMap#8]
Hi Carsen,

Thanks for the Python GUI it is really nice and works for most video. I had issues with some videos see link (https://www.dropbox.com/sh/czy3mvswuyfpfek/AADaHVUWqs_U9cgn3w5RFI4Wa?dl=0) that return the following 
![image](https://user-images.githubusercontent.com/34900992/57781029-5e251900-76f7-11e9-9cda-c001a862fd65.png)
Do you have any recommendations?

**Comment by carsen-stringer** [comment]
for this I'd try installing the development version of pims if you haven't already
```
pip install git+https://github.com/soft-matter/pims.git
```

**Comment by carsen-stringer** [comment]
FYI I've been having quite a few issues with pims on windows that I didn't have on linux so this may require more work to fix

**Comment by juplab** [comment]
thanks I have tried with pims and on linux as well same issue on linux. I will try different format

**Comment by juplab** [comment]
Hi Carsen,
changing the scale of the resolution of the video with ffpmeg solved the problem ffmpeg -vf scale=800:-1

**Comment by obarnstedt** [comment]
Hi,
I am having the same problem that has been described above, on macOS 10.13.6, despite installing the PIMS development version. Interestingly, some videos (e.g. obtained from calcium imaging) work, while our behavioural videos acquired through Basler Pylon software (MP4) all show the reshaping error. Converting these videos as suggested by juplab above does indeed solve the issue, but unfortunately this is not a feasible solution for all of our data. It'd be great if a better solution could be found.
Thank you for all your work!
Oliver
