### ISSUE TITLE
About pose_tracking_cli_tutorial.md file

### ISSUE THREAD

**Issue by yiiiichennn-w** [MouseLand/facemap#82]
Thanks for the great work! Could you please finish the pose_tracking_cli_tutorial.md file? Thanks in advance!

**Comment by yiiiichennn-w** [comment]
Thanks for the great work! Could you please finish the pose_tracking_cli_tutorial.md file? Thanks in advance!

**Comment by Atika-Syeda** [comment]
thanks for your interest. We will keep you posted as the new features are added.
