### ISSUE TITLE
Issue saving large files with np.save

### ISSUE THREAD

**Issue by mckennabrown** [MouseLand/facemap#83]
Hi! I believe the `np.save` function call in `process.py` doesn’t set the pickle protocol high enough for large files.
```
computed projection chunk 790 / 804, time  6570.38sec
computed projection chunk 800 / 804, time  6650.71sec
Computed motSVD projection at 6667.93s
Traceback (most recent call last):
  File “[]\Anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py”, line 1255, in process_ROIs
    savename = process.run(
  File “[]\Anaconda3\envs\facemap\lib\site-packages\facemap\process.py”, line 856, in run
    savename = save(proc, savepath)
  File “[]\Anaconda3\envs\facemap\lib\site-packages\facemap\process.py”, line 599, in save
    np.save(savename, proc)
  File “<__array_function__ internals>“, line 180, in save
  File “[]\Anaconda3\envs\facemap\lib\site-packages\numpy\lib\npyio.py”, line 522, in save
    format.write_array(fid, arr, allow_pickle=allow_pickle,
  File “[]\Anaconda3\envs\facemap\lib\site-packages\numpy\lib\format.py”, line 700, in write_array
    pickle.dump(array, fp, protocol=3, **pickle_kwargs)
OverflowError: serializing a bytes object larger than 4 GiB requires pickle protocol 4 or higher
```
Additional context: Here I had set a pupil ROI and checked motSVD through the python GUI with a large mp4 file. The `facemap` version installed is from the main branch on Jan 19, on anaconda3 on Windows.
1GB did appear to save, although with `np.load(fn,allow_pickle=True)` I get the error message `EOFError: Ran out of input`.

**Comment by Atika-Syeda** [comment]
Hi @mckennabrown, could you please share the numpy and python version that's being used. You can find it in your terminal's output or by running `pip list` in the conda environment which should also give you facemap's version.

**Comment by Atika-Syeda** [comment]
Hi, I'd suggest if you could please try trimming and processing smaller videos while we fix the issue.
