### ISSUE TITLE
DOC: <process multi non-sequential videos>

### ISSUE THREAD

**Issue by nelson-hc** [MouseLand/facemap#85]
### Issue with current documentation:

Is there any way to process SVDs for multi-non-sequential videos?

**Comment by Atika-Syeda** [comment]
Hi @nelson-hc, perhaps you'd find the last code chunk in this notebook helpful: https://github.com/MouseLand/facemap/blob/main/notebooks/process.ipynb

**Comment by nelson-hc** [comment]
Hi @Atika-Syeda, how do I run the code from the command line?

**Comment by nelson-hc** [comment]
Hi @Atika-Syeda, when I tried to run it on jupyter notebook, it gave me this error: UnboundLocalError: local variable 'Ly' referenced before assignment.

**Comment by Atika-Syeda** [comment]
HI @nelson-hc can you please share which version of facemap you're using?
