### ISSUE TITLE
menu bar with only a ‘file’ button?

### ISSUE THREAD

**Issue by PathwayinGithub** [MouseLand/facemap#89]
### Describe the issue:

I try to run facemap. Successfully, it can do the ROI and SVD processing.
But the menu bar has only a 'file' button which is just used to load movies and processed files, so I can not use the functions of pose tracking and neural activity prediction.
I have checked my conda list and pip list, all packages needed have been installed. What's more, I have tried on different devices including PC and Mac.( I want to use facemap on Windows.)
How can I deal with the problem? Thanks.

### Provide environment info:

     active environment : facemap
    active env location : /Users/****/opt/anaconda3/envs/facemap
            shell level : 2
       user config file : /Users/****/.condarc
 populated config files : /Users/****/.condarc
          conda version : 22.9.0
    conda-build version : 3.22.0
         python version : 3.9.13.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/****/opt/anaconda3  (writable)
      conda av data dir : /Users/****/opt/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/****/opt/anaconda3/pkgs
                          /Users/****/.conda/pkgs
       envs directories : /Users/****/opt/anaconda3/envs
                          /Users/****/.conda/envs
               platform : osx-64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.9.13 Darwin/21.6.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False

**Comment by Atika-Syeda** [comment]
Hi @PathwayinGithub could you please share screenshot of the GUI and output of `conda list`?

**Comment by PathwayinGithub** [comment]
> 
@Atika-Syeda Hi! I start the facemap in the terminal of my macbook and here is 'OMP Info'. I don't know whether it is related to the problem, but the error  isn't seen when I use windows.  Here is only a file button on both mac and windows. 
(base)  ~ % conda activate facemap
(facemap)  ~ % python -m facemap
OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/102808765/222976592-7076d9f2-3462-4127-b3d2-6043940b6541.png">

**Comment by VivoNeuro** [comment]
Hello, I have the same problem on Windows10, the menu bar has only the file button. Could you help me? Thank you!

**Comment by VivoNeuro** [comment]
Hi Atika-Syeda,

Below I am sending you, thank you!

(base) C:\>conda activate facemap

(facemap) C:\>python -m facemap
no sklearn for reduced rank

(facemap) C:\>conda list
# packages in environment at C:\Users\*****\.conda\envs\facemap:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
ca-certificates           2023.01.10           haa95532_0
certifi                   2022.12.7        py38haa95532_0
facemap                   0.2.0                    pypi_0    pypi
importlib-metadata        6.0.0                    pypi_0    pypi
intel-openmp              2021.4.0          haa95532_3556
libffi                    3.4.2                hd77b12b_6
llvmlite                  0.39.1                   pypi_0    pypi
mkl                       2021.4.0           haa95532_640
mkl-service               2.4.0            py38h2bbff1b_0
mkl_fft                   1.3.1            py38h277e83a_0
mkl_random                1.2.2            py38hf11a4ad_0
natsort                   8.3.1                    pypi_0    pypi
numba                     0.56.4                   pypi_0    pypi
numpy                     1.23.5           py38h3b20f71_0
numpy-base                1.23.5           py38h4da318b_0
opencv-python             4.7.0.72                 pypi_0    pypi
openssl                   1.1.1t               h2bbff1b_0
pip                       23.0.1           py38haa95532_0
pyqt5                     5.15.9                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.11.1                  pypi_0    pypi
pyqtgraph                 0.11.0rc0                pypi_0    pypi
python                    3.8.16               h6244533_3
scipy                     1.10.1                   pypi_0    pypi
setuptools                65.6.3           py38haa95532_0
six                       1.16.0             pyhd3eb1b0_1
sqlite                    3.40.1               h2bbff1b_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.38.4           py38haa95532_0
wincertstore              0.2              py38haa95532_2
zipp                      3.15.0                   pypi_0    pypi

(facemap) C:\>

**Comment by VivoNeuro** [comment]
Hi Atika-Syeda,

Could you help me with the menu bar problem above?
Thank you

**Comment by Atika-Syeda** [comment]
Hi @VivoNeuro  the pyqtgraph version does not match ours. Can you please try pip installing the latest version of facemap and let us know if the problem still persists.
