### ISSUE TITLE
motion energy as roi type

### ISSUE THREAD

**Issue by imgross** [MouseLand/FaceMap#9]
Hi Carsen,

thanks for setting up this cool GUI ! As we talked in the Data Science course it would be great to also have an ROI type that is able to read out absolute motion energy. In my case it would be for extracting time points when my arm moves into the FOV of the camera.

Cheers,
Isa-Maria

**Comment by carsen-stringer** [comment]
This has now been added as field "motion" to the _proc.npy output file :)

**Comment by phanhuynh** [comment]
Hi Carsen, sometimes my _proc.npy output file does not contain the field 'motion'.  Do you know what could be causing this:  dict_keys(['filenames', 'save_path', 'Ly', 'Lx', 'sbin', 'fullSVD', 'save_mat', 'Lybin', 'Lxbin', 'sybin', 'sxbin', 'LYbin', 'LXbin', 'avgframe', 'avgmotion', 'avgframe_reshape', 'avgmotion_reshape', 'motion', 'motSv', 'movSv', 'motMask', 'movMask', 'motMask_reshape', 'movMask_reshape', 'motSVD', 'movSVD', 'pupil', 'running', 'blink', 'rois', 'sy', 'sx'])
