### ISSUE TITLE
BUG?: File format problem? - 

### ISSUE THREAD

**Issue by rozmar** [MouseLand/facemap#90]
### Version information:

numpy version: 1.23.5
python version: 3.8.13

### Describe the issue:

Image not rendered when I try to click on "Add ROI" button, also error message (below).
![image](https://user-images.githubusercontent.com/6236396/220232734-cf0a3fee-41da-4be2-b8b0-4648cb3b9120.png)
If I select a ROI, weird ROI appears on the main GUI window, cannot be pulled down vertically:
![image](https://user-images.githubusercontent.com/6236396/220232985-8b030210-3c71-40b2-bb3b-c0ca78a410f5.png)

At the end, the predictions are all around the place, even outside the image, so the reason might be that the data format is incorrect.
![image](https://user-images.githubusercontent.com/6236396/220417148-19d3b684-cd5a-444d-bbcb-890542337fd7.png)

I am saving the movies with a custom python script:
https://github.com/rozmar/pySpinCapture/
This is the writer:
writer = skvideo.io.FFmpegWriter(movieName, outputdict={'-vcodec': 'h264_nvenc', '-crf': str(crfOut), '-threads': str(ffmpegThreads)})

Here is a sample movie:
https://drive.google.com/file/d/1PsA4pv6YZnRxYMRt2Mu7QjxKoQiYeF6G/view?usp=share_link

### Error message:

```shell
Traceback (most recent call last):
  File "/home/rozmar/anaconda3/envs/facemap/lib/python3.8/site-packages/pyqtgraph/graphicsItems/ImageItem.py", line 866, in paint
    self.render()
  File "/home/rozmar/anaconda3/envs/facemap/lib/python3.8/site-packages/pyqtgraph/graphicsItems/ImageItem.py", line 583, in render
    qimage = self._try_make_qimage(image, levels, lut, augmented_alpha)
  File "/home/rozmar/anaconda3/envs/facemap/lib/python3.8/site-packages/pyqtgraph/graphicsItems/ImageItem.py", line 855, in _try_make_qimage
    raise ValueError("unsupported image type")
ValueError: unsupported image type
```

**Comment by Atika-Syeda** [comment]
Hi @rozmar thanks for your detailed issue. Please pull the updated code from the main branch that should've fixed the bug.

**Comment by rozmar** [comment]
Thank you for the quick response and help!
It works like a charm indeed.
