### ISSUE TITLE
BUG: Fine-tuning GUI shows cropped and downsampled image

### ISSUE THREAD

**Issue by rozmar** [MouseLand/facemap#93]
### Version information:

numpy version: 1.23.5
python version: 3.8.13

### Describe the issue:

Hi there! The tracking looks promising out of the box!

When fine-tuning the model, the image is cropped, and not the same way the cropping was set up. It's cropped even when cropping is not enabled (no ROI).

cropping:
![image](https://user-images.githubusercontent.com/6236396/220788761-509e50d2-38ad-4637-8af6-0e9287ad0c31.png)

refinement gui:
![image](https://user-images.githubusercontent.com/6236396/220788076-14d42f1d-8f36-430a-bab2-1d831d713422.png)

The other thing is that the image here is downsampled, and it would be easier to fine-tune the model on the original images for the annotator. (This is a lower priority problem, the cropping is the bigger one.)

Similar frame from the original movie:
![image](https://user-images.githubusercontent.com/6236396/220788324-d2fa56f5-b6f8-42bb-9b1e-824945fba74d.png)

**Comment by rozmar** [comment]
Sorry I closed the issue by accident :)

**Comment by Atika-Syeda** [comment]
Hi @rozmar, I have attached example screenshots showing how I ran the pipeline. We suggest using a bounding box to focus on the face so cropping will be useful. Please follow the instructions for [refinement](https://github.com/MouseLand/facemap/blob/main/docs/pose_tracking_gui_tutorial.md#finetune-model-to-refine-keypoints-for-a-video). After re-training and saving the model I'd suggest restarting the GUI. To generate keypoints using the refined model make sure to select the correct model name in the dropdown menu before processing. Please let me know if this doesn't work and share any CLI output to check whether the right model is used for prediction. 

Thanks for the suggestion for using non-downsampled frames during refinement. We will look into it.
![img3](https://user-images.githubusercontent.com/47366160/220990618-6ae4e1ff-cf2e-406f-bdff-6574f8cd10f7.png)
![img2](https://user-images.githubusercontent.com/47366160/220990621-0e2f9b79-8121-4deb-8d99-4f798dca9cb6.png)
![img1](https://user-images.githubusercontent.com/47366160/220990622-a3d54201-683d-4cc2-96c4-04dec40068a4.png)

**Comment by rozmar** [comment]
Hi @Atika-Syeda !
You are right, I omitted the bounding box and that's why the predictions were off. Thank you!

But the predictions are great even if I use a huge bounding box
![image](https://user-images.githubusercontent.com/6236396/221003004-c1c0caa4-65f7-4c96-a31e-e6aeb8dc50ba.png)
That suggests to me that there is a bug in the bounding-box-free version.

**Comment by Atika-Syeda** [comment]
We've trained the model on images focused on the face so we suggest similar views to be used for prediction. If you load a new video (cropped using bbox parameters printed in CLI) and process w/o bounding box it should give you same prediction as your current video w/ bounding box. 
In the prediction above could you please confirm whether the base model or your fine-tuned model was used for prediction? It should be in the output of your CLI: "Loading model state from: ..."

**Comment by rozmar** [comment]
Also, how can predictions be outside of the bounding box, and outside of the image?

**Comment by Atika-Syeda** [comment]
You're right. There was some issue related to bbox estimation which should now be fixed in the dev branch. Please pull the changes from the dev branch if you'd like to use that version. I'll address your query regarding predictions outside bbox soon and hopefully it will be included in the next update on the main branch.

**Comment by rozmar** [comment]
@Atika-Syeda 
Should I swap to the main branch? Is this change already merged?
I wonder if it would be a quick fix to replace the low-res image with a high-res version for refinement.
My videos are not perfect for seeing the whiskers, but this downsampling makes the job impossible for me.
Thanks,
Marton

**Comment by Atika-Syeda** [comment]
Hi @rozmar yes please update to the latest version of facemap where you should be able to zoom in/out of the frames for labelling and the aspect ratio is preserved.
