### ISSUE TITLE
npy file was not generated for neural activity. 

### ISSUE THREAD

**Issue by jonben3215** [MouseLand/facemap#97]
### Feature you'd like to see: FILE  NOT FOUND. 

Unable to get the Neural Activity to work. Documentation states that there is a .npy file that I can be loaded into the program to track neural activity but none of the file generated can be loaded. And the tutorial github gives a 404 error. Where can I get the np file for the Neural Activity?

**Comment by Atika-Syeda** [comment]
Hi @jonben3215, the GUI does not generate any files for neural data. We expect the user to have neural recordings saved as a numpy array in a .npy file that can be loaded in the GUI. You can find the pose tracking GUI tutorial [here](https://github.com/MouseLand/facemap/blob/main/docs/pose_tracking_gui_tutorial.md) and the SVD tutorial [here](https://github.com/MouseLand/facemap/blob/main/docs/svd_python_tutorial.md).
