### ISSUE TITLE
QGraphicsScene::removeItem:  output 

### ISSUE THREAD

**Issue by lmontelisciani** [MouseLand/facemap#98]
### Issue with current documentation:

Hi, I have the following output after running FaceMap GUI using only the CPU on a video of 1h, and I was wondering if it is a problem or not since I cannot find anything like this in the doc.

Thanks in advance for any help.

ROI setting:
- motion SVD
- ROI on the whole image
- SVD spatial bin: 4

Process setting:
- motSVD
- Save *.mat
- multivideo 

Computed motSVD projection at 387.44s
run time 433.04s
QGraphicsScene::removeItem: item 0x20f3e5e2290's scene (0x0) is different from this scene (0x20f3570e0a0)
QGraphicsScene::removeItem: item 0x20f3e5e2290's scene (0x0) is different from this scene (0x20f3570e0a0)
QGraphicsScene::removeItem: item 0x20f3e5e2290's scene (0x0) is different from this scene (0x20f3570e0a0)
Output saved in C:/Users/Luca Montelisciani/OneDrive/Desktop/FM

**Comment by Atika-Syeda** [comment]
Hi @lmontelisciani, that's just a warning sign and should not affect any of the output. We'll try to remove it in the future. It's safe to ignore it and you should find the motion SVD saved in C:/Users/Luca Montelisciani/OneDrive/Desktop/FM.

**Comment by lmontelisciani** [comment]
Thanks for confirming!
